plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.github.axet.bookreader'
    compileSdk 35
//    ndkVersion '16.1.4479499' // stripReleaseDebugSymbols

    defaultConfig {
        applicationId "com.github.axet.bookreader"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
    }

    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            output.outputFileName = org.apache.commons.io.FilenameUtils.getExtension(android.defaultConfig.applicationId) + "-" + (output.getFilter(com.android.build.OutputFile.ABI) ?: "universal") + "-" + android.defaultConfig.versionName + "-" + variant.buildType.name + ".apk"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

configurations { // TODO fix library dependency copy
    resolvableImpl.extendsFrom(implementation)
    resolvableImpl.canBeResolved(true)
}

dependencies {
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support:support-vector-drawable:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:2.0.4'

    implementation 'com.github.axet.fbreader:library:0.1.18'
    implementation 'com.github.axet:android-library:1.35.21'

//    implementation(libs.axet.android.library)
    implementation(libs.axet.djvulibre)
    implementation(libs.axet.pdfium)
    implementation(libs.axet.k2pdfopt)
    implementation(libs.axet.wget) { exclude group: 'org.json', module: 'json' }

//    implementation libs.appcompat
//    implementation libs.material

}